### PR TITLE
Refactoring conditional directives for incomplete if conditions.

### PR DESCRIPTION
**Pull request by wmarquesr**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.

* [Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
* [Living in the #ifdef Hell](https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/)

It might improve code understanding, maintainability and error-proneness.

### CODE REVIEW

**Comment by davidok8** [comment]
Hi @wmarquesr,

First welcome and thank you for trying to contribute. I feel however compelled to summarily reject this very PR and explain why.

- First and foremost the contribution is not directly related with my library but with a third-party library.
- Besides you broke the Windows build, which should have made you realize that maintaining an old library like *libpng* is not that trivial! (even I don't have the expertise -- and no intention -- to maintain it except upgrading it.)

Best.

**Comment by wmarquesr** [comment]
I'm sorry, i don't realize it was another lib. 
Butm what you think about that kind of refactoring ?

**Comment by RomeroMalaquias** [comment]
Hello @davidok8   i'm from the same research team of wmarquesr and i need to ask if you prefer this code before or after the commit. What do you think about this kind of change? 
Thanks in advance.

**Comment by RomeroMalaquias** [comment]
I mean, would you accept if it was not for the fact we submitted the pull request to a code written by third parties?

**Pull request closed without merging**
